### ISSUE TITLE
Run with `--type-check` flag enabled

### ISSUE THREAD

**Issue by janslow** [SublimeLinter/SublimeLinter-tslint#15]
`tslint@3.14.0` added support for rules having type information when linting.

This requires a `--project` (with the path of `tsconfig.json`) and `--type-check` arguments to be provided.

It would therefore be useful to support these rules in this plugin.

**Comment by lavrton** [comment]
Hello. I can not do this right now, but Pull Request is welcome!

**Comment by janslow** [comment]
I've started [a branch](https://github.com/janslow/SublimeLinter-contrib-tslint/tree/feature/type-check) on my fork which implements this, however it has a major performance hit at the moment (as it compiles and validates the entire project)

Hopefully, when [this TSLint issue](https://github.com/palantir/tslint/issues/1603) is fixed, this performance hit will be reduced.

**Comment by jussikinnula** [comment]
Hi @janslow!

I was able to get `tslint` to work together with Sublime by using your fork, but actually needing to remove the `--type-check` (nowadays it seems that tslint requires `--project` anyways in order to function).

Just wondering if you're using still using `tslint` with Sublime, and if you have any ideas how to cope with the issue - that `/var/folders/**/*.tsx` and `/var/folders/**/*.ts` need to be in the project's `tsconfig.json` includes in order for `tslint` to be able to work?

It's not a big problem, but it might be nice to be able to use for example a command line option in `tslint` to add more includes, since by default without any includes `tsconfig.json` project only treats child directories with `.ts` and `.tsx` -files correctly (personally I used `src/**/*.tsx`, `src/**/*.ts`, `/var/folders/**/*.tsx` and `/var/folders/**/*.ts` for includes to get everything working).

**Comment by jussikinnula** [comment]
Secondly, @janslow & @lavrton the linked TSLint issue is closed already. I would re-edit the patch to actually only use `--project` (not `--type-check`, and of course increase the version requirement to latest `tslint`), and then do PR.

Or maybe even @lavrton consider handing the project over to @janslow if it would keep the Sublime-Linter-tslint in functional order for several years to come :-) ...

**Comment by lavrton** [comment]
Can't fix the issue now by myself. But I am happy to apply useful Pull Requests.

**Comment by jussikinnula** [comment]
@lavrton, I did make a pull request based on @janslow's fork. I did also write some documentation how to use SublimeLinter-contrib-tslint in general.

Still, at the moment I wouldn't consider even with this patch the set complete. More work would be needed on tslint & TypeScript side to support linting in Sublime.

**Comment by braver** [comment]
--type-check has been [deprecated](https://github.com/palantir/tslint/commit/349d1b8f6b09699fdc979e7c0f417a302e1e5440), and we support a project setting, so I guess we're done here?
