### ISSUE TITLE
Weird results when used in combination with Vue

### ISSUE THREAD

**Issue by HeleenE** [SublimeLinter/SublimeLinter-tslint#40]
When linting a .vue file I get errors which don't seem to be related with the line they're displayed on. Also the console shows the following warning: 

```
SublimeLinter: WARNING: Reported line '19' is not within the code we're linting.
Maybe the linter reports problems from multiple files or `line_col_base` is not set correctly.
```

Is it possible to use tslint within Sublime within Vue files?

**Comment by kaste** [comment]
Hi @HeleenE,

afaik tslint cannot lint whole vue files. Maybe there is a plugin for that?

**Comment by HeleenE** [comment]
@kaste that's to bad! I've been trying to get it up and running, but not having much succes. Is there a way to tell SublimeLinter/tslint to only lint the code in the `<script>` tags?

**Comment by kaste** [comment]
Probably, take a look at http://www.sublimelinter.com/en/stable/linter_settings.html#selector

It usually depends on how good the Vue syntax definition is.

**Comment by HeleenE** [comment]
With these settings it seems to only report errors within the script tags, but they still don't correspond with the code and I still get the error in the console. Any ideas?

**Comment by kaste** [comment]
Have you tried turning on `debug` in the SublimeLinter settings? It should print the raw output from tslint. Does tslint actually lint across files?

**Comment by braver** [comment]
You probably need to set up TSLint in a way that it can deal with the vue files. IIRC TSLint usually is pretty lame in combination with partial code snippets, i.e. without a project so it can build type info. 

In any case, since the maintainers here don't use TS in combination with Vue a lot, we need at least a whole lot more debug info to work with, an example project/file, and probably someone who knows how all of this is supposed to work in the first place. As it is, this issue is not actionable, so I'm closing it until further notice.
